# Site settings
title: Chien-Yu Huang's Blog
author: Chien-Yu Huang (Denny)
email: denny.cyhuang1230@gmail.com
description: >
 Chien-Yu Huang, a Software Engineer in Garena Taiwan.
baseurl: ""
url: "https://cyhuang1230.github.io"
github_username: cyhuang1230

# Build settings
#markdown: kramdown
#markdown: rdiscount

# Custom
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->

# mirror Github settings
safe: true
lsi: false
theme: jekyll-theme-dinky