# Site settings
title: Chien-Yu Huang's Blog
author: Chien-Yu Huang (Denny)
email: denny.cyhuang1230@gmail.com
description: >
 Chien-Yu Huang, a Software Engineer in Yahoo! Taiwan.
baseurl: ""
url: "https://cyhuang1230.github.io"
github_username: cyhuang1230 

# Build settings
#markdown: kramdown
#markdown: rdiscount

# Custom
permalink: /:year/:month/:title/

# mirror Github settings
safe: true
lsi: false